### ISSUE TITLE
Do not include binaries in GitHub

### ISSUE THREAD

**Issue by B3none** [Kxnrl/RankMe-Tag#1]
It's best practice to use the releases tab.

**Comment by Kxnrl** [comment]
lol, last commit from 2 years ago
you can check my other repo

**Comment by B3none** [comment]
I was going to publish my version but figured may as well improve the one that's already out there ;P

**Comment by Kxnrl** [comment]
thanks

**Comment by B3none** [comment]
https://www.youtube.com/watch?v=9PA-F6ip9uY
